name: build-and-test-pipeline
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t descriptive-stats-demo .
    
    - name: Lint
      run: docker run --rm --entrypoint pylint descriptive-stats-demo **/*.py
    
    - name: Run Unit Tests
      run: docker run --rm --entrypoint pytest descriptive-stats-demo test_stats_demo.py
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: publicfacingdemosltd
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Tag and Push to Registry
      run: |
        IMAGE_TAG=publicfacingdemosltd/descriptive-stats-demo:${GITHUB_REF#refs/heads/}-$(date +%Y%m%d%H%M%S)

        docker tag descriptive-stats-demo $IMAGE_TAG
        docker push $IMAGE_TAG
